package be.axa.deploy.openshift.client

class OC{

    public static final String OPENSHIFT_TOKEN_ID = "Openshift_token" 
    public static final String OPENSHIFT_TOKEN_PRD_ID = "Openshift_token_prd" 

    public static final String CMD = "/appl/oc_client/oc"
    public static final String LOGIN = "login"
    public static final String TOKEN = "--token"
    public static final String PROJECT = "project"
    public static final String ROLLOUT_LATEST = "rollout latest"
    public static final String DEPLOY_CONFIG = "dc/"
    public static final String CREATE_SECRET = "create secret generic"
    public static final String FROM_LOCAL_FILE = "--from-file"
    public static final String DRY_RUN = "--dry-run -o yaml"
    public static final String APPLY = "/appl/oc_client/oc apply -f -"
    public static final String VOLUME = "volume"
    public static final String OVERWRITE = "--overwrite"
    public static final String ADD = "--add"
    public static final String TYPE = "--type"
    public static final String SECRET = "secret"
    public static final String SECRET_NAME = "--secret-name"
    public static final String MOUNT_PATH = "--mount-path"
    public static final String NAME = "--name"
    public static final String SET_TRIGGERS = "set triggers"
    public static final String CONTAINERS = "--containers"
    public static final String FROM_IMAGE = "--from-image"
    public static final String SET_PROBE = "set probe"
    public static final String READINESS = "--readiness"
    public static final String LIVENESS = "--liveness"
    public static final String ECHO_OK = "-- echo ok"
    public static final String GET_URL_HTTP = "--get-url=http://:8080/"
    public static final String REMOVE = "--remove"
    public static final String GET_POD = "get pod"
    public static final String SELECTOR = "--selector"    
    public static final String TAG = "tag"
    public static final String BUILD = "start-build"
    public static final String GET_NAME_ONLY = "--short"
    public static final String FROM_CURRENT_DIRECTORY = "--from-dir=."
    public static final String STREAM_LOGS_TO_STDOUT = "--follow"


    public static final String SEPARATOR = " "    
    public static final String EQUALS = "="
    public static final String HIDE_CMD = "#!/bin/sh -e\n"
    public static final String OR = "||"
    public static final String AND = " | "
    public static final String EMPTY_STRING = "null"
}